"""The study repository port: what the use cases need from storage.

``SqlStudyRepo`` implements it against PostgreSQL (RLS); tests use an in-memory
fake with the same per-user semantics.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date, datetime
from typing import Any, Protocol
from uuid import UUID


class StudyRepo(Protocol):
    async def commit(self) -> None: ...
    async def release(self) -> None: ...
    async def rebind(self) -> None: ...
    async def get_profile(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def save_profile(self, user_id: UUID, data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_plans_from(self, user_id: UUID, day: date) -> None: ...
    async def get_plan(self, user_id: UUID, day: date) -> dict[str, Any] | None: ...
    async def save_plan(self, user_id: UUID, plan: dict[str, Any]) -> datetime: ...
    async def chunk_for_user(self, user_id: UUID, chunk_id: UUID) -> dict[str, Any] | None: ...
    async def chunks_for_user(
        self, user_id: UUID, source_id: UUID | None, chunk_ids: Sequence[UUID], limit: int
    ) -> list[dict[str, Any]]: ...
    async def insert_card(self, user_id: UUID, card: dict[str, Any]) -> dict[str, Any]: ...
    async def get_card(self, user_id: UUID, card_id: UUID) -> dict[str, Any] | None: ...
    async def due_cards(
        self, user_id: UUID, now: datetime, limit: int, new_limit: int
    ) -> list[dict[str, Any]]: ...
    async def counts(
        self, user_id: UUID, now: datetime, day_start: datetime
    ) -> dict[str, int]: ...
    async def apply_review(
        self, user_id: UUID, card: dict[str, Any], review: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def topic_cards(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def reviews_since(self, user_id: UUID, since: datetime) -> list[dict[str, Any]]: ...
    # Real planner signals (ADR 0014, study depth).
    async def approved_weights(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def question_attempts(
        self, user_id: UUID, since: datetime
    ) -> list[dict[str, Any]]: ...
    async def question_counts(self, user_id: UUID) -> list[dict[str, Any]]: ...
    # Baseline diagnostic.
    async def baseline_candidates(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def latest_baseline(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def create_baseline(
        self, user_id: UUID, systems: dict[str, str], minutes: int, now: datetime
    ) -> dict[str, Any]: ...
    async def baseline_exam(self, user_id: UUID, exam_id: UUID) -> dict[str, Any] | None: ...
    async def finish_baseline(
        self, user_id: UUID, baseline_id: UUID, submitted_at: datetime,
        results: Sequence[dict[str, Any]],
    ) -> None: ...
    # Weekly reports.
    async def reviews_between(
        self, user_id: UUID, start: datetime, end: datetime
    ) -> list[dict[str, Any]]: ...
    async def attempts_between(
        self, user_id: UUID, start: datetime, end: datetime
    ) -> list[dict[str, Any]]: ...
    async def save_report(
        self, user_id: UUID, week_start: date, version: int, report: dict[str, Any]
    ) -> datetime: ...
    async def latest_report(self, user_id: UUID) -> dict[str, Any] | None: ...
