"""The study repository port: what the use cases need from storage.

``SqlStudyRepo`` implements it against PostgreSQL (RLS); tests use an in-memory
fake with the same per-user semantics.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date, datetime
from typing import Any, Protocol
from uuid import UUID


class StudyRepo(Protocol):
    async def commit(self) -> None: ...
    async def release(self) -> None: ...
    async def rebind(self) -> None: ...
    async def get_profile(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def save_profile(self, user_id: UUID, data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_plans_from(self, user_id: UUID, day: date) -> None: ...
    async def get_plan(self, user_id: UUID, day: date) -> dict[str, Any] | None: ...
    async def save_plan(self, user_id: UUID, plan: dict[str, Any]) -> datetime: ...
    async def chunk_for_user(self, user_id: UUID, chunk_id: UUID) -> dict[str, Any] | None: ...
    async def chunks_for_user(
        self, user_id: UUID, source_id: UUID | None, chunk_ids: Sequence[UUID], limit: int
    ) -> list[dict[str, Any]]: ...
    async def insert_card(self, user_id: UUID, card: dict[str, Any]) -> dict[str, Any]: ...
    async def get_card(self, user_id: UUID, card_id: UUID) -> dict[str, Any] | None: ...
    async def due_cards(
        self, user_id: UUID, now: datetime, limit: int, new_limit: int
    ) -> list[dict[str, Any]]: ...
    async def counts(
        self, user_id: UUID, now: datetime, day_start: datetime
    ) -> dict[str, int]: ...
    async def apply_review(
        self, user_id: UUID, card: dict[str, Any], review: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def topic_cards(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def reviews_since(self, user_id: UUID, since: datetime) -> list[dict[str, Any]]: ...
    # Real planner signals (ADR 0014, study depth).
    async def approved_weights(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def question_attempts(
        self, user_id: UUID, since: datetime
    ) -> list[dict[str, Any]]: ...
    async def question_counts(self, user_id: UUID) -> list[dict[str, Any]]: ...
    # Baseline diagnostic.
    async def baseline_candidates(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def latest_baseline(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def create_baseline(
        self, user_id: UUID, systems: dict[str, str], minutes: int, now: datetime
    ) -> dict[str, Any]: ...
    async def baseline_exam(self, user_id: UUID, exam_id: UUID) -> dict[str, Any] | None: ...
    async def finish_baseline(
        self, user_id: UUID, baseline_id: UUID, submitted_at: datetime,
        results: Sequence[dict[str, Any]],
    ) -> None: ...
    # Weekly reports.
    async def reviews_between(
        self, user_id: UUID, start: datetime, end: datetime
    ) -> list[dict[str, Any]]: ...
    async def attempts_between(
        self, user_id: UUID, start: datetime, end: datetime
    ) -> list[dict[str, Any]]: ...
    async def save_report(
        self, user_id: UUID, week_start: date, version: int, report: dict[str, Any]
    ) -> datetime: ...
    async def latest_report(self, user_id: UUID) -> dict[str, Any] | None: ...
    # Weakness loop: a card rated Again queues a re-test of a question on its chunk.
    async def record_lapse(
        self, user_id: UUID, card: Mapping[str, Any], review_id: UUID, now: datetime
    ) -> None: ...


class SessionRepo(StudyRepo, Protocol):
    """Today sessions and progress insights (ADR 0024)."""

    async def get_session(self, user_id: UUID, day: date) -> dict[str, Any] | None: ...
    async def get_session_by_id(
        self, user_id: UUID, session_id: UUID
    ) -> dict[str, Any] | None: ...
    async def create_session(
        self, user_id: UUID, day: date, versions: tuple[int, int],
        steps: Sequence[Mapping[str, Any]],
    ) -> dict[str, Any]: ...
    async def update_step(
        self, user_id: UUID, session_id: UUID, step_no: int, changes: Mapping[str, Any]
    ) -> None: ...
    async def finish_session(
        self, user_id: UUID, session_id: UUID, summary: Mapping[str, Any], now: datetime
    ) -> None: ...
    async def completed_sessions(self, user_id: UUID, since: date) -> list[dict[str, Any]]: ...
    async def cards_by_ids(self, user_id: UUID, ids: Sequence[UUID]) -> list[dict[str, Any]]: ...
    async def figures_by_ids(
        self, user_id: UUID, ids: Sequence[UUID]
    ) -> list[dict[str, Any]]: ...
    async def learn_material(
        self, user_id: UUID, codes: Sequence[str], limit: int, figures: int
    ) -> tuple[list[str], list[str]]: ...
    async def question_candidates(
        self, user_id: UUID, types: Sequence[str]
    ) -> list[dict[str, Any]]: ...
    async def open_retests(self, user_id: UUID, limit: int) -> list[dict[str, Any]]: ...
    async def questions_by_ids(
        self, user_id: UUID, ids: Sequence[UUID]
    ) -> dict[str, dict[str, Any]]: ...
    async def question_locked(self, user_id: UUID, question_id: UUID) -> bool: ...
    async def record_sba(
        self, user_id: UUID, question: Mapping[str, Any], graded: Mapping[str, Any],
        confidence: int | None, session_id: UUID, now: datetime,
    ) -> UUID | None: ...
    async def submit_viva(
        self, user_id: UUID, question: Mapping[str, Any], answer: str
    ) -> dict[str, Any] | None: ...
    async def viva_exam(self, user_id: UUID, exam_id: UUID) -> dict[str, Any] | None: ...
    async def coverage_stats(self, user_id: UUID, since: datetime) -> list[dict[str, Any]]: ...
    async def rated_attempts(self, user_id: UUID, since: datetime) -> list[dict[str, Any]]: ...


class KnowledgeCardRepo(StudyRepo, Protocol):
    """Cloze cards from verified claims and image cards from figures (ADR 0029)."""

    async def cloze_candidates(
        self, user_id: UUID, source_id: UUID | None, topic: str | None, limit: int
    ) -> list[dict[str, Any]]: ...
    async def figure_candidates(
        self, user_id: UUID, source_id: UUID | None, topic: str | None, limit: int
    ) -> list[dict[str, Any]]: ...
    async def insert_knowledge_card(
        self, user_id: UUID, card: dict[str, Any]
    ) -> dict[str, Any] | None: ...
